Henning task 1
Walingar/Java-Rostock-2020 pull request #1
Opened 2020-06-06 10:15 UTC by hediriro

Ok, submission... maybe this works here

2020-06-20 21:20 UTC, Walingar requested changes

2020-06-20 21:20 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                int blueNew=0;
Don't forget about code style ;)

2020-06-20 21:20 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                        if ((imageRow + rowNavigator > -1) && (imageRow + rowNavigator < output.length) && (imageColumn + columnNavigator > -1) && (imageColumn + columnNavigator < output[imageRow].le
Extract variable `imageRow + rowNavigator`

2020-06-20 21:20 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            redTemp = (int)Math.floor(redTemp * kernel[kernelRow][kernelColumn]);
You can just cast it to int without Math.floor, it is useless operation

2020-06-20 21:20 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            redNew = redNew + redTemp;
You can remove redTemp and use `+=` operator

2020-07-01 21:51 UTC, Walingar requested changes

2020-07-01 21:51 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            redNew += redTemp;
I mean that you can remove `redTemp` and use `renNew += (int) ...`

2020-07-01 21:51 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            int greenTemp = image[imageRow + rowNavigator][imageColumn + columnNavigator].getGreen();
You have already extracted `imageRowCorrection` and `imageColumnCorrection` but don't use it here

2020-07-01 21:51 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            int greenTemp = image[imageRow + rowNavigator][imageColumn + columnNavigator].getGreen();
You can extract variable with `image[imageRow + rowNavigator][imageColumn + columnNavigator]`

2020-07-13 08:07 UTC, Walingar requested changes

2020-07-13 08:07 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            int redTemp = pixel.getRed();
These temp variables are redundant

2020-07-13 08:07 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            redNew += (int)(redTemp * kernel[kernelRow][kernelColumn]);
`kernel[kernelRow][kernelColumn]` can be extracted

2020-07-13 08:07 UTC, Walingar commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +    private boolean isInRange(int imageRowCorrection, int imageSizeRow, int imageColumnCorrection, int imageSizeColumn){
code-style

2020-07-13 10:51 UTC, hediriro commented on src/main/java/impl/image/ConvolutionProviderImpl.java
> +                            redNew += (int)(redTemp * kernel[kernelRow][kernelColumn]);
I forgot to apply this before re-requesting reviw, sorry! However, I already applied it afterwards.

2020-07-19 13:53 UTC, Walingar approved these changes

2020-07-19 13:53 UTC, merged