Homework 5: Tom Liefke
Walingar/Java-Rostock-2020 pull request #10
Opened 2020-07-11 22:11 UTC by tommymowe

2020-07-13 08:24 UTC, Walingar requested changes

2020-07-13 08:24 UTC, Walingar commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
Please, remove this file from Git. It's redundant here

2020-07-13 08:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            return inputStreamReader;
You can just write `return new InputStreamReader(inputStream, fileEncoding)`

2020-07-13 08:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +
redundant empty line

2020-07-13 08:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            e.printStackTrace();
don't use printStackTrace in your code. It will print non-userfriendly message

2020-07-13 08:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            Writer writer = new OutputStreamWriter(outputStream, fileEncoding);
Writer is not closed

2020-07-13 08:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +    public void write(File file, InputStream data, Charset dataEncoding, Charset fileEncoding) {
You don't create new file here, but you should

2020-07-13 08:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            writer.flush();
Flush will be executed before close automaticaly

2020-07-13 08:24 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            Writer writer = new OutputStreamWriter(outputStream, fileEncoding);
It's better to use buffered implementations

2020-07-22 16:19 UTC, tommymowe commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
After deleting this file, nothing works.. all tests are failing and i dont now why.

2020-07-22 16:58 UTC, tommymowe commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
How can i delete a.txt from git?

2020-07-23 12:17 UTC, Walingar commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
You can create a commit which removes this file

2020-07-23 12:19 UTC, Walingar commented on temp/dir1/dir2/a.txt
> +Какая-то другая строчка
> all tests are failing and i dont now why

I told about it on the previous lecture

2020-07-23 12:19 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +    public void write(File file, InputStream data, Charset dataEncoding, Charset fileEncoding) {
It's the reason why your tests are failing

2020-07-23 12:21 UTC, Walingar requested changes

2020-07-23 12:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            reader.transferTo(writer);
If there exception occurs than writer won't be closed, so it's better to use try with resources

2020-07-27 09:31 UTC, Walingar approved these changes

2020-07-27 09:31 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                if (!checkDirectoryCreation || !checkFileCreation){
code-style

2020-07-27 09:31 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            Reader reader = new InputStreamReader(data, dataEncoding);
I should repeat:  it's better to use try with resources

2020-07-27 09:31 UTC, merged