Henning task 2
Walingar/Java-Rostock-2020 pull request #3
Opened 2020-06-10 13:38 UTC by hediriro

Submission of my 2nd homework.

2020-06-20 21:26 UTC, Walingar commented
Please, rename PR to proper naming

2020-06-20 21:31 UTC, Walingar requested changes

2020-06-20 21:31 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        if (expression == null){
code-style

2020-06-20 21:31 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +            throw new IllegalArgumentException();
Exception message?

2020-06-20 21:31 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        expression = expression.replaceAll("\\s+", ""); // remove whitespaces
It is not cool to use such thing in this task. There are few reasons: 
1. It doesn't allow to use this solution in streams like task when you have a huge string which gives to you char by char
2. It uses x2 memory which is not required and can be solved using constant memory
3. Regex expressions can take exponential time in some cases. You can read about it in dragon book. And you should be sure that if you use regexp it will take linear time

2020-06-20 21:31 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        expression = expression.replaceAll("\\s+", ""); // remove whitespaces
So please, don't use it here

2020-06-28 11:46 UTC, hediriro commented
> Please, rename PR to proper naming

What does "PR" mean?

2020-07-01 22:02 UTC, Walingar requested changes

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                if (Character.isLetter(currentElement)) {
It is not the best solution because what if this string will contain some special symbols like '#' or another one which are not letters, so it is better to check that given string contains '-', '+' or number and overwise throw an exception

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                        long checkIntOrLong = Long.parseLong(parsedInteger);
Try to rewrite your solution to not to use long

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                        parsedOperator = "" + currentElement;
you always do this, so you can rewrite this `if` a little bit

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        String parsedOperator = "";
it can be char, isn't it?

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                                if (checkIntRange >= Integer.MAX_VALUE || checkIntRange <= Integer.MIN_VALUE) {
Maybe standard library contains the same checks and you can reduce your code?

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                    parsedInteger += currentElement;
String is immutable, so if you use += to String then new String will be created and all previous characters will be copied. Thus, your solution works in O(n^2)

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                        if (checkIntOrLong > Integer.MAX_VALUE || checkIntOrLong < Integer.MIN_VALUE) {
Do you really need this check? Did you watch at parseInt documentation?

2020-07-01 22:02 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        int firstRelevantCharacter = 0;
It's quite hard to understand what this variable means, relevant for what? And do you really need it?

2020-07-13 08:10 UTC, Walingar requested changes

2020-07-13 08:10 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                } else if (currentElement == '-' || (currentElement == '+')) {
redundant brackets here: (currentElement == '+')

2020-07-13 08:10 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +        for (int stringIndex = 0; stringIndex < stringLength; stringIndex++) {
You don't use stringIndex, so this for can be replaced with for (char currentChar: ...)

2020-07-13 08:10 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    private int safeAdd(int left, int right) {
Missed empty line

2020-07-13 08:10 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    private int safeAdd(int left, int right) {
safeAdd and safeSubtract are already implemented in standart library

2020-07-13 08:10 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +            if (!parsedIntegerString.isEmpty()) {
is this check required?

2020-07-13 11:00 UTC, hediriro commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +            if (!parsedIntegerString.isEmpty()) {
Yes, otherwise when parsing an empty String an error occurs instead of assigning 0 to the int

2020-07-13 11:15 UTC, hediriro commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +            if (!parsedIntegerString.isEmpty()) {
Ok, no it wasn't necessary. Found a better way to make this check earlier skipping useless operations

2020-07-13 12:57 UTC, hediriro commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +    private int safeAdd(int left, int right) {
Yes, however I receive AssertionError instead of expected ArithmeticException when using Interger.sum(a, b);

2020-07-19 13:58 UTC, Walingar requested changes

2020-07-19 13:58 UTC, Walingar commented on src/main/java/impl/expression/ExpressionParserImpl.java
> +                    isNegative = currentChar == '-';
As I told on the lecture, this code can be better. We can remove isNegative check at all and just always add '-' or '+' to the `parsedIntegerBuilder` here

2020-07-23 07:59 UTC, Walingar approved these changes

2020-07-23 07:59 UTC, merged