Homework 3: Henning Richter
Walingar/Java-Rostock-2020 pull request #5
Opened 2020-06-30 20:36 UTC by hediriro

2020-07-01 22:20 UTC, Walingar requested changes

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueFactory.java
> +    private static int capacity;
You use static fields here, so you can't create more than one ArrayIntQueue :(

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueFactory.java
> +public class ArrayQueueFactory implements IntQueue {
Factory shouldn't implement this interface. You need to create another class like `ArrayIntQueue` and return it's instance in getInstance method

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueFactory.java
> +    private static int currentSize;
You don't use this field

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueFactory.java
> +    public int getSize() {
It uses linear time, but should use constant time

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueFactory.java
> +            for (int newPosition = 0; newPosition < capacity; newPosition++) {
It uses linear time but should use contant time

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +class QueueNode {
Java file should contain only one class

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +public class LinkedQueueFactory implements IntQueue {
The same mistake as with ArrayQueueFactory.

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +class QueueNode {
You can move this class inside another class. You can read more here https://docs.oracle.com/javase/tutorial/java/javaOO/nested.html

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +    public QueueNode getPrevious() {
You don't use this method

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +    public void setPrevious(QueueNode previous) {
You sets previous but don't get it

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +    private static QueueNode queueLinked;
queueLinked -> linkedQueue as in english

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +            while (assist.getNext() != null) {
it takes linear time but shoud take constant time

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +                queueLinked = queueLinked.getNext();
You are calling queueLinked.getNext() twice

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +        if (currentSize == 0) {
you can inline this variable here: if (getSize() == 0) {...}

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +                size += 1;
size++

2020-07-01 22:20 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueFactory.java
> +    public int getSize() {
This method takes linear time, but should take constant time

2020-07-13 08:17 UTC, Walingar requested changes

2020-07-13 08:17 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueNode.java
> +public class LinkedQueueNode {
it's better to make it nested

2020-07-13 08:17 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueImpl.java
> +    private int currentShift;
I guess it is better to rename it to "headIndex", isn't it?

2020-07-13 08:17 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueImpl.java
> +    private int currentSize;
just `size` `current` is redundant

2020-07-13 08:17 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueImpl.java
> +            if (currentIndex >= capacity) {
Can we use `%` here?

2020-07-19 14:00 UTC, Walingar requested changes

2020-07-19 14:00 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueImpl.java
> +    class LinkedQueueNode {
You can mark it as static

2020-07-19 14:00 UTC, Walingar commented on src/main/java/impl/queue/ArrayQueueImpl.java
> +        if (size == capacity) {
ArrayQueueImpl and LinkedQueueImpl contain similar part of code like this check, so extract it to an abstract class. Use all OOP power!

2020-07-20 12:09 UTC, hediriro commented on src/main/java/impl/queue/ArrayQueueImpl.java
> +        if (size == capacity) {
Actually, I don't think that an abstract class would improve this code here. There are only few similarites, the most in if conditions where the else block differs tremendously. I don't think, that I could just overwrite the else block for each instanciation. Thus, an abstract class would only make sense for getSize(), but creating an abstract class just for saving one method so incredibly small, doesn't seem to be worth the effort from my point of view.

2020-07-20 15:16 UTC, hediriro commented
Sorry for changing somtething again before re-requesting your review, but I thought afterwards that removing these unnecessary getters and setters might be senseful.

2020-07-23 08:00 UTC, Walingar requested changes

2020-07-23 08:00 UTC, Walingar commented on src/main/java/impl/queue/LinkedQueueImpl.java
> +import api.queue.IntQueue;
redundant import

2020-07-27 09:21 UTC, Walingar approved these changes

2020-07-27 09:21 UTC, merged