Homework 4: Henning Richter
Walingar/Java-Rostock-2020 pull request #6
Opened 2020-07-02 14:00 UTC by hediriro

2020-07-13 08:43 UTC, Walingar requested changes

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParserImpl.java
> +                    } else parsedTemperatureBuilder.append(currentElement);
missed { }

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParserImpl.java
> +                    if (currentElement == '-') {
is it required? parseInt can parse negative integers too

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParserImpl.java
> +    public DayTemperatureInfo parse(String expression) {
https://en.wikipedia.org/wiki/Recursive_descent_parser you can read this article it will be better to use this method here. But it is not required

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParserImpl.java
> +            char currentElement = expression.charAt(stringIndex);
You don't use stringIndex here, so you can rewrite it like `for (char currentChar: ...)`

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        yearTemperatures = new HashMap<>(monthCapacity);
The left part of Map is `enum` so you can use EnumMap implementation it is more effictive

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        monthCapacity = 0;
HashMap is auto-extendable, so you can miss it

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    public YearTemperatureStatsImpl(){
code-style

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        Map<Month, Integer> output = new HashMap<>(monthCapacity);
It's not cool to use `monthCapacity` here, because it can require additional memory if information about few month only exsited

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            Map<Integer, DayTemperatureInfo> dayTemperatures = new HashMap<>(month.length(false));
you can use putIfAbsent here

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +                sum += day.getTemperature();
This solution takes linear time, but should take constant

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        } else {
it is better to write 
```
if (!yearTemperatures.containsKey(month)) {
  return null;
}
```

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        for (Map<Integer, DayTemperatureInfo> eachMonth : knownMonths) {
for (Map<Integer, DayTemperatureInfo> eachMonth : yearTemperatures.values())

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            for (DayTemperatureInfo eachDay : knownDays) {
This solution takes linear time but should take constant per each month

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        List<DayTemperatureInfo> output = new ArrayList<>(month.length(false));
If we know information about few days only than otput will take a lot of additional memory

2020-07-13 08:43 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +                            output.add(previousDayIndex + 1, eachDay);
This solution takes O(n^2) time but should take O(nlogn)

2020-07-19 14:05 UTC, Walingar requested changes

2020-07-19 14:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    public ArrayList<DayTemperatureInfo> mergeSort(ArrayList<DayTemperatureInfo> whole) {
mergeSort is already implemented in standart library :)

2020-07-19 14:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            return mergeSort(output);
How to you check the insertion order if some days have similar temperature?

2020-07-19 14:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    public Double getAverageTemperature(Month month) {
This method still have linear complexity but should have constant

2020-07-19 14:05 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private final Map<Month, Integer> maxTemperatures;
What if you will want to know more stats about month? (e.g. averageTemp, minimalTemp, etc.) Will you write more maps? It's not OOP style. It is better to create Map<Month, MonthInfo> and keep stats inside MonthInfo

2020-07-20 14:22 UTC, hediriro commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private final Map<Month, Integer> maxTemperatures;
Applied that. However, this made getMaxTemperature() slightly linear again and not constant, as it requires a specific Map as output.

2020-07-23 08:03 UTC, Walingar requested changes

2020-07-23 08:03 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            ArrayList<DayTemperatureInfo> output = new ArrayList<>(knownDays.size());
Use interface instead of implementation

2020-07-23 08:03 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            ArrayList<DayTemperatureInfo> output = new ArrayList<>(knownDays.size());
You can simply write `List<DayTemperatureInfo> output = new ArrayList<>(temperatures.values());`

2020-07-27 09:23 UTC, Walingar approved these changes
Cool!

2020-07-27 09:23 UTC, merged