Homework 5: Henning Richter
Walingar/Java-Rostock-2020 pull request #8
Opened 2020-07-05 15:29 UTC by hediriro

…dingWriter

2020-07-13 08:21 UTC, Walingar requested changes

2020-07-13 08:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            Reader output = new InputStreamReader(fileStream, fileEncoding);
You can inline this variable (just return `new InputStreamReader(fileStream, fileEncoding)`)

2020-07-13 08:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingReaderImpl.java
> +            e.printStackTrace();
don't use printStackTrace in your code. It will print non-userfriendly message

2020-07-13 08:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.getParentFile().mkdirs();
What if directories won't be created what would be done?

2020-07-13 08:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            file.createNewFile();
The same thing for file creation. File may not be created and execution will be continued

2020-07-13 08:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            Writer writer = new OutputStreamWriter(outputStream, fileEncoding);
Writer is not closed

2020-07-13 08:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            writer.flush();
Flush will be executed before closing

2020-07-13 08:21 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +            Writer writer = new OutputStreamWriter(outputStream, fileEncoding);
It's better to use buffered implementations

2020-07-13 13:50 UTC, hediriro commented
Hey Nick, sorry for adding after re-requesting again! I just haven't predicted GutHub build failing, as all my tests passed.

2020-07-19 14:07 UTC, Walingar requested changes

2020-07-19 14:07 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                execute(file, data, dataEncoding, fileEncoding);
copy paste of `execute(file, data, dataEncoding, fileEncoding)`. It's better to write if (!file.exists()) { ... return; } ...

2020-07-19 14:07 UTC, Walingar commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +        writer.close();
writer won't be closed if for example transferTo throw an exception. Use try with resources

2020-07-20 12:57 UTC, hediriro commented on src/main/java/impl/file/FileEncodingWriterImpl.java
> +                execute(file, data, dataEncoding, fileEncoding);
Actually, I don't understand why an inverted if is better than my solution before. It works like this: If the file exists, just write to existing file. Otherwise, check if you can create a new file. If a new file was created, write to that new file. if not, do nothing, as this method is void.

2020-07-23 08:00 UTC, Walingar approved these changes

2020-07-23 08:01 UTC, merged