Homework 4: Tom Liefke
Walingar/Java-Rostock-2020 pull request #9
Opened 2020-07-11 22:10 UTC by tommymowe

2020-07-13 09:00 UTC, Walingar requested changes

2020-07-13 09:00 UTC, Walingar commented on src/test/kotlin/impl/weather/DayTemperatureInfoImplParserTest.kt
> +internal class DayTemperatureInfoImplParserTest {
Please, don't change test sources )

2020-07-13 09:00 UTC, Walingar commented on src/main/java/api/weather/YearTemperatureStats.java
>  public interface YearTemperatureStats {
And don't change interfaces, too :)

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +        if(this.getTemperature() > o.getTemperature()) return 1;
code-style

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +        if(this.getTemperature() > o.getTemperature()) return 1;
it can be replaced with `return getTemperature() - o.getTemperature()`

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +
redundant empty line

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParser.java
> +public class DayTemperatureInfoParser implements api.weather.DayTemperatureInfoParser {
It is better to use different name, because it intersect with interface. Use e.g. `DayTemperatureInfoParserImpl`

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParser.java
> +                    if (currentElement == '-') {
is it required? parseInt can parse negative integers too

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParser.java
> +                    } else temperatureString.append(currentElement);
missed { }

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParser.java
> +        for (int stringIterator = 0; stringIterator < stringLength; stringIterator++) {
You don't use stringIterator here, so you can rewrite it like for (char currentChar: ...)

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParser.java
> +    public DayTemperatureInfo parse(String rawData) {
https://en.wikipedia.org/wiki/Recursive_descent_parser you can read this article it will be better to use this method here. But it is not required

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    public YearTemperatureStatsImpl(){
code-style

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +    private Map<Month, Map<Integer, DayTemperatureInfoImpl>> weatherMap;
can be marked as final

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        weatherMap = new HashMap<>();
The left part of Map is enum so you can use EnumMap implementation it is more effictive

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +
you can use putIfAbsent here

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            for (DayTemperatureInfoImpl day : elements) {
This solution takes linear time, but should take constant

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        if (weatherMap.containsKey(month) == true) {
You can remove == true

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            for (DayTemperatureInfoImpl day : days) {
This solution takes linear time, but should take constant per each month

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +        List<DayTemperatureInfoImpl> emptyList= new ArrayList<DayTemperatureInfoImpl>();
code-style

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            Collections.sort(output);
How do you check the insertion order if days have same temperatures?

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +
redundant empty line

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +            return null;
it's better to write single return null in the end

2020-07-13 09:00 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +
redundant empty lines

2020-07-22 17:01 UTC, tommymowe commented on src/main/java/api/weather/YearTemperatureStats.java
>  public interface YearTemperatureStats {
i tried really, but it wouldn't work if i didnt change it

2020-07-22 17:02 UTC, tommymowe commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +        if(this.getTemperature() > o.getTemperature()) return 1;
should i change it the way you provided it in the lecture or should i stay with way i solved it?

2020-07-22 17:10 UTC, tommymowe commented on src/test/kotlin/impl/weather/DayTemperatureInfoImplParserTest.kt
> +internal class DayTemperatureInfoImplParserTest {
i tried so hard with this task, but it's probalby the naming which fuck up my code.. i tried to work with IDE to get the tests work.. all changes where suggestet by the IntelliJ.. 
The Main Problem is, that im so confused by the naming of all my classes and interfaces, that i cant get an overview or an idea how to fix all this things.. i thought it would work if i use it constantly the same way.

2020-07-23 12:23 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoImpl.java
> +        if(this.getTemperature() > o.getTemperature()) return 1;
It's better to replace it with `return getTemperature() - o.getTemperature()`. It's more readable

2020-07-23 12:24 UTC, Walingar commented on src/main/java/api/weather/YearTemperatureStats.java
>  public interface YearTemperatureStats {
Then you should rewrite your code in another way

2020-07-23 12:25 UTC, Walingar commented on src/test/kotlin/impl/weather/DayTemperatureInfoImplParserTest.kt
> +internal class DayTemperatureInfoImplParserTest {
You can try to write the solution from the beginning... But test sources and interfaces shouldn't be changed

2020-07-27 09:29 UTC, Walingar requested changes

2020-07-27 09:29 UTC, Walingar commented on src/main/java/api/weather/YearTemperatureStats.java
> +import impl.weather.DayTemperatureInfoImpl;
redundant import

2020-07-27 09:29 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParser.java
> +        //TEMPERATURE
space between // and comment

2020-07-27 09:29 UTC, Walingar commented on src/main/java/impl/weather/DayTemperatureInfoParser.java
> +public class DayTemperatureInfoParser implements api.weather.DayTemperatureInfoParser {
I should repeat again: It is better to use different name, because it intersect with interface. Use e.g. DayTemperatureInfoParserImpl

2020-07-27 09:29 UTC, Walingar commented on src/main/java/impl/weather/YearTemperatureStatsImpl.java
> +                averageTemperature = (((quantityOfDays-1)*averageTemperature)+temperature)/quantityOfDays;
code-style

2020-07-27 09:29 UTC, Walingar approved these changes

2020-07-27 09:29 UTC, merged